// Code generated by qb-generator; DO NOT EDIT.

package pgmodel

import "git.ultraware.nl/Ultraware/qb/v2"

///// PgAttribute /////
var (
	qbPgAttributeTable = qb.Table{Name: `pg_attribute`}

	qbPgAttributeFAttname      = qb.TableField{Parent: &qbPgAttributeTable, Name: `attname`}
	qbPgAttributeFAtttypid     = qb.TableField{Parent: &qbPgAttributeTable, Name: `atttypid`}
	qbPgAttributeFAttlen       = qb.TableField{Parent: &qbPgAttributeTable, Name: `attlen`}
	qbPgAttributeFAtttypmod    = qb.TableField{Parent: &qbPgAttributeTable, Name: `atttypmod`}
	qbPgAttributeFAttrelid     = qb.TableField{Parent: &qbPgAttributeTable, Name: `attrelid`}
	qbPgAttributeFAttnotnull   = qb.TableField{Parent: &qbPgAttributeTable, Name: `attnotnull`}
	qbPgAttributeFAttnum       = qb.TableField{Parent: &qbPgAttributeTable, Name: `attnum`}
	qbPgAttributeFAttisdropped = qb.TableField{Parent: &qbPgAttributeTable, Name: `attisdropped`}
)

// PgAttributeType represents the table "PgAttribute"
type PgAttributeType struct {
	Attname      qb.Field
	Atttypid     qb.Field
	Attlen       qb.Field
	Atttypmod    qb.Field
	Attrelid     qb.Field
	Attnotnull   qb.Field
	Attnum       qb.Field
	Attisdropped qb.Field
	table        *qb.Table
}

// GetTable returns an object with info about the table
func (t *PgAttributeType) GetTable() *qb.Table {
	return t.table
}

// Select starts a SELECT query
func (t *PgAttributeType) Select(f ...qb.Field) *qb.SelectBuilder {
	return t.table.Select(f)
}

// Delete creates a DELETE query
func (t *PgAttributeType) Delete(c1 qb.Condition, c ...qb.Condition) qb.Query {
	return t.table.Delete(c1, c...)
}

// Update starts an UPDATE query
func (t *PgAttributeType) Update() *qb.UpdateBuilder {
	return t.table.Update()
}

// Insert starts an INSERT query
func (t *PgAttributeType) Insert(f ...qb.Field) *qb.InsertBuilder {
	return t.table.Insert(f)
}

// PgAttribute returns a new PgAttributeType
func PgAttribute() *PgAttributeType {
	table := qbPgAttributeTable
	return &PgAttributeType{
		qbPgAttributeFAttname.Copy(&table),
		qbPgAttributeFAtttypid.Copy(&table),
		qbPgAttributeFAttlen.Copy(&table),
		qbPgAttributeFAtttypmod.Copy(&table),
		qbPgAttributeFAttrelid.Copy(&table),
		qbPgAttributeFAttnotnull.Copy(&table),
		qbPgAttributeFAttnum.Copy(&table),
		qbPgAttributeFAttisdropped.Copy(&table),
		&table,
	}
}

///// Tables /////
var (
	qbTablesTable = qb.Table{Name: `information_schema.tables`}

	qbTablesFTableName   = qb.TableField{Parent: &qbTablesTable, Name: `table_name`}
	qbTablesFTableSchema = qb.TableField{Parent: &qbTablesTable, Name: `table_schema`}
)

// TablesType represents the table "Tables"
type TablesType struct {
	TableName   qb.Field
	TableSchema qb.Field
	table       *qb.Table
}

// GetTable returns an object with info about the table
func (t *TablesType) GetTable() *qb.Table {
	return t.table
}

// Select starts a SELECT query
func (t *TablesType) Select(f ...qb.Field) *qb.SelectBuilder {
	return t.table.Select(f)
}

// Delete creates a DELETE query
func (t *TablesType) Delete(c1 qb.Condition, c ...qb.Condition) qb.Query {
	return t.table.Delete(c1, c...)
}

// Update starts an UPDATE query
func (t *TablesType) Update() *qb.UpdateBuilder {
	return t.table.Update()
}

// Insert starts an INSERT query
func (t *TablesType) Insert(f ...qb.Field) *qb.InsertBuilder {
	return t.table.Insert(f)
}

// Tables returns a new TablesType
func Tables() *TablesType {
	table := qbTablesTable
	return &TablesType{
		qbTablesFTableName.Copy(&table),
		qbTablesFTableSchema.Copy(&table),
		&table,
	}
}

///// Columns /////
var (
	qbColumnsTable = qb.Table{Name: `information_schema.columns`}

	qbColumnsFColumnName             = qb.TableField{Parent: &qbColumnsTable, Name: `column_name`}
	qbColumnsFTableSchema            = qb.TableField{Parent: &qbColumnsTable, Name: `table_schema`}
	qbColumnsFTableName              = qb.TableField{Parent: &qbColumnsTable, Name: `table_name`}
	qbColumnsFCharacterMaximumLength = qb.TableField{Parent: &qbColumnsTable, Name: `character_maximum_length`}
)

// ColumnsType represents the table "Columns"
type ColumnsType struct {
	ColumnName             qb.Field
	TableSchema            qb.Field
	TableName              qb.Field
	CharacterMaximumLength qb.Field
	table                  *qb.Table
}

// GetTable returns an object with info about the table
func (t *ColumnsType) GetTable() *qb.Table {
	return t.table
}

// Select starts a SELECT query
func (t *ColumnsType) Select(f ...qb.Field) *qb.SelectBuilder {
	return t.table.Select(f)
}

// Delete creates a DELETE query
func (t *ColumnsType) Delete(c1 qb.Condition, c ...qb.Condition) qb.Query {
	return t.table.Delete(c1, c...)
}

// Update starts an UPDATE query
func (t *ColumnsType) Update() *qb.UpdateBuilder {
	return t.table.Update()
}

// Insert starts an INSERT query
func (t *ColumnsType) Insert(f ...qb.Field) *qb.InsertBuilder {
	return t.table.Insert(f)
}

// Columns returns a new ColumnsType
func Columns() *ColumnsType {
	table := qbColumnsTable
	return &ColumnsType{
		qbColumnsFColumnName.Copy(&table),
		qbColumnsFTableSchema.Copy(&table),
		qbColumnsFTableName.Copy(&table),
		qbColumnsFCharacterMaximumLength.Copy(&table),
		&table,
	}
}
