---
kind: pipeline
type: docker
name: Linux

platform:
  go: &go
    image: registry.ultraware.nl/ultraware/go-build:latest
    pull: always

steps:
  - name: setup
    <<: *go
    commands:
      - make setup

  - name: setup sqlserver
    <<: *go
    commands:
      - sleep 10

      - go env -w "GOPRIVATE=git.ultraware.nl/*/*"
      - go install git.ultraware.nl/Go/sqlcmd@latest

      - sqlcmd internal/tests/scripts/sqlserver/create_database.sql

      - export DATABASE_CONNECTION_STRING="$DATABASE_CONNECTION_STRING?database=qb_test"
      - sqlcmd internal/tests/scripts/sqlserver/create_login.sql
    environment:
      DATABASE_CONNECTION_STRING: sqlserver://sa:P@ssw0rd@sqlserver
  
  - name: test
    <<: *go
    commands:
      - make test
      - make lint
      - go test -bench=.

  - name: PostgresSQL
    <<: *go
    commands:
      - make test_postgres
    environment:
      POSTGRES_TESTHOST: pgsql

  - name: MSSQL
    <<: *go
    environment:
      MSSQL_TESTHOST: sqlserver
    commands:
      - make test_mssql

  - name: MySQL
    <<: *go
    environment:
      MYSQL_TESTHOST: mariadb
    commands:
      - make test_mysql

  - name: Total coverage
    <<: *go
    commands:
      - cat unit.out > total.out
      - tail -n +2 postgres.out >> total.out
      - tail -n +2 mysql.out >> total.out
      - tail -n +2 mssql.out >> total.out
      - go tool cover -func total.out | tail -1

services:
  - name: pgsql
    image: postgres:10.1-alpine
    pull: always
    environment:
      DB_HOST: postgres
      POSTGRES_USER: qb_test
      POSTGRES_DB: qb_test

  - name: mariadb
    image: mariadb:10.3
    pull: always
    environment:
      MYSQL_DATABASE: qb_test
      MYSQL_USER: qb_test
      MYSQL_PASSWORD: qb_test
      MYSQL_ALLOW_EMPTY_PASSWORD: true

  - name: sqlserver
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: P@ssw0rd
