run:
  build-tags: []

output:
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - err113
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  govet:
    enable:
      - shadow

  gocyclo:
    min-complexity: 15

  lll:
    line-length: 150
    tab-width: 4

  nakedret:
    max-func-lines: 10

  funlen:
    lines: 120
    statements: 60

issues:
  exclude: []
  exclude-rules:
    - linters:
        - stylecheck
      text: "ST1000:"
    - path: _test.go
      linters:
        - lll
        - funlen
        - dupl
    - linters:
        - revive
      text: "package-comments|exported"
    - linters:
        - errcheck
      source: "defer .*Rollback()"
    - linters:
        - errcheck
      source: "defer .*Close()"
  exclude-use-default: false
  max-same-issues: 0
