version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - err113
    - errcheck
    - errorlint
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - lll
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    funlen:
      lines: 120
      statements: 60
    gocyclo:
      min-complexity: 15
    govet:
      enable:
        - shadow
    lll:
      line-length: 150
      tab-width: 4
    nakedret:
      max-func-lines: 10
  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: 'ST1000:'
      - linters:
          - dupl
          - funlen
          - lll
        path: _test.go
      - linters:
          - revive
        text: package-comments|exported
      - linters:
          - errcheck
        source: defer .*Rollback()
      - linters:
          - errcheck
        source: defer .*Close()
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
